### ISSUE TITLE
move to citation-file-format organization?

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/doi2cff#3]
Hey Stefan, 
nice tool. Should we move it to https://github.com/citation-file-format/ ?

**Comment by sverhoeven** [comment]
I made this to improve the speed of making *.cff files. Moving it to a better place is OK for me.

**Comment by jspaaks** [comment]
Hi @sdruskat:
is this tool something worth having under the ``citation-file-format`` organization?

**Comment by sdruskat** [comment]
Hi @jspaaks and @sverhoeven:
Absolutely, this is a **great** tool! Please do move it.

For the sake of simplicity, should I just add either or both of you as owners to the org?

**Comment by sdruskat** [comment]
Also, do you mind me publicizing the progress - including your tools - on Twitter, etc.?

**Comment by jspaaks** [comment]
Fine with me if Stefan remains the owner. And publicizing on Twitter is good for us too, so no problem there.

**Comment by sdruskat** [comment]
Thanks. @sverhoeven I've invited you to the org, and will need to make you Admin of the project once it's moved, so please ping me if it has :).

**Comment by sverhoeven** [comment]
@sdruskat the repo has been moved. I also renamed it to better reflect what it does. 

Could you make me admin so I can setup the CI and readthedocs?

**Comment by sdruskat** [comment]
@sverhoeven Ace! Have invited you as a collaborator with Admin rights.

**Comment by sverhoeven** [comment]
Completed the integrations.
